title: Hazem Elbaz
position: Assistant Professor
affiliation: Alaqsa University - Palestine
email: hazem_baz@alaqsa.edu.ps
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=Ei_icn0AAAAJ&hl=en
github_link: https://github.com/hazemelbaz
linkedin: https://www.linkedin.com/in/hazem-elbaz-9b7aa628
orcid: https://orcid.org/0000-0002-0623-0929
avatar: ./assets/img/HazemPic.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
